version: "3.8"

services:
  fruit:
    image: fruit-service:1.0
    container_name: fruit
    ports:
      - "8083:8083"
    networks:
      - fruit-basket

  basket:
    image: basket-service:1.0
    container_name: basket
    ports:
      - "8082:8082"
    networks:
      - fruit-basket
    depends_on:
      - fruit

networks:
  fruit-basket:
    driver: bridge  #Serves to make the "bridge" between the 2 microServices
