############################################
# HTTP (BasketService)
############################################
quarkus.http.port=8082

############################################
# POSTGRESQL (Docker Runtime)
############################################
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/frutas_db
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

############################################
# REST CLIENT (FruitService)
############################################
quarkus.rest-client."org.client.FruitClient".url=http://fruit:8083

############################################
# KAFKA Producer (Basket → Fruit)
############################################
mp.messaging.outgoing.basket-events-out.connector=smallrye-kafka
mp.messaging.outgoing.basket-events-out.topic=basket-events
mp.messaging.outgoing.basket-events-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.basket-events-out.bootstrap.servers=kafka:9092

############################################
# Disable Kafka DevServices
############################################
quarkus.kafka.devservices.enabled=false

############################################
# TEST MODE (BasketService)
############################################
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/frutas_db
%test.quarkus.datasource.username=postgres
%test.quarkus.datasource.password=postgres
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.http.test-port=8002

%test.mp.messaging.outgoing.basket-events-out.bootstrap.servers=localhost:9092
