############################################
# HTTP (FruitService)
############################################
quarkus.http.port=8083

############################################
# POSTGRESQL (Docker Runtime)
############################################
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/frutas_db
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

############################################
# KAFKA Consumer (Fruit ← Basket)
############################################
mp.messaging.incoming.basket-events-in.connector=smallrye-kafka
# Makes connection between channel and topic
mp.messaging.incoming.basket-events-in.topic=basket-events
mp.messaging.incoming.basket-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.basket-events-in.group.id=fruit-service-group
mp.messaging.incoming.basket-events-in.bootstrap.servers=kafka:9092

############################################
# Disable Kafka DevServices
############################################
quarkus.kafka.devservices.enabled=false

############################################
# TEST MODE — H2 (simples e sem dependências)
############################################
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:frutas_db;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa

# recria as tabelas automaticamente nos testes
%test.quarkus.hibernate-orm.database.generation=drop-and-create

# Kafka ignorado nos testes (não impede arranque)
%test.mp.messaging.incoming.basket-events-in.bootstrap.servers=localhost:9092
