quarkus.http.port=8083

# Base de dados H2 puramente em memória (Não precisa de Docker nem cria ficheiros em disco)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:frutas_db;DB_CLOSE_DELAY=-1

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true