quarkus.http.port=8082

# O link mágico que liga os dois microsserviços via HTTP
quarkus.rest-client."org.client.FruitClient".url=http://localhost:8083

# Base de dados própria do Basket (também em memória, totalmente isolada)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:basket_db;DB_CLOSE_DELAY=-1

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true